apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-backend
  namespace: bank-namespace
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bank-backend
  template:
    metadata:
      labels:
        app: bank-backend
    spec:
      containers:
        - name: bank-backend
          image: 172.17.78.58:8000/bank/bank-app:1.0
          ports:
            - containerPort: 8080
