apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bank-namespace
type: Opaque
data:
  mysql-root-password: cm9vdA== # base64 for 'root'
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: bank-namespace
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bank-namespace
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE       # <-- Added this
              value: bank                # <-- Added this
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
