apiVersion: v1
kind: Service
metadata:
  name: bank-backend
  namespace: bank
spec:
  type: ClusterIP
  selector:
    app: bank-backend
  ports:
    - port: 80         # port inside cluster
      targetPort: 8080 # port your container listens on
