apiVersion: v1
kind: Service
metadata:
  name: bank-app
  namespace: bank-namespace
  labels:
    app: bank-app
spec:
  type: ClusterIP
  selector:
    app: bank-app
  ports:
    - port: 80
      targetPort: 8089
      protocol: TCP