apiVersion: v1
kind: Service
metadata:
  name: bank-backend
  namespace: bank-namespace
  labels:
    app: bank-backend
spec:
  type: ClusterIP
  selector:
    app: bank-backend
  ports:
    - port: 80
      targetPort: 8080
